name = "ChainedArrays"
uuid = "154148eb-a451-4506-8097-cb641d95622d"
authors = ["Paul Nemec <paul.nemec@tum.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
